version: '3'

services:
  database:
    image: "postgres" # use latest official postgres version
    environment:
      # credentials
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=footballdatabase
    ports:
      - "5438:5432"

  testing_database:
    image: "postgres" # use latest official postgres version
    environment:
      # credentials
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testFootballdatabase
    ports:
      - "5434:5432"
volumes:
  testing_database_data: # named volumes can be managed easier using docker-compose
