"""empty message

Revision ID: 22cecaacebd8
Revises: f57859043bf7
Create Date: 2021-10-23 22:01:01.378183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cecaacebd8'
down_revision = 'f57859043bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('fixture_unique', 'fixture', ['fixture_date', 'away_id', 'home_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fixture_unique', 'fixture', type_='unique')
    # ### end Alembic commands ###
