"""empty message

Revision ID: bfadb1cc94b8
Revises: 
Create Date: 2021-06-17 14:57:37.480834

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bfadb1cc94b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('email', sa.String(length=128), nullable=False),
                    sa.Column('password', sa.String(length=192), nullable=False),
                    sa.Column('role', sa.SmallInteger(), nullable=False),
                    sa.Column('status', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('league',
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('max_teams', sa.BigInteger(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('player',
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('date_of_birth', sa.Date(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('preferred_position', sa.String(length=255), nullable=True),
                    sa.Column('shirt_number', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('season',
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('end_year', sa.Date(), nullable=False),
                    sa.Column('start_year', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('team',
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('date_founded', sa.Date(), nullable=True),
                    sa.Column('location', sa.String(length=255), nullable=True),
                    sa.Column('manager', sa.String(length=255), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('league_team',
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('date_joined', sa.Date(), nullable=True),
                    sa.Column('league_id', sa.BigInteger(), nullable=False),
                    sa.Column('season_id', sa.BigInteger(), nullable=False),
                    sa.Column('team_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
                    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
                    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('team_player',
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('date_joined', sa.Date(), nullable=True),
                    sa.Column('player_id', sa.BigInteger(), nullable=False),
                    sa.Column('team_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
                    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('fixture',
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_modified', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('away_score', sa.BigInteger(), nullable=True),
                    sa.Column('fixture_date', sa.Date(), nullable=False),
                    sa.Column('fixture_time', sa.String(length=255), nullable=True),
                    sa.Column('home_score', sa.BigInteger(), nullable=True),
                    sa.Column('match_week', sa.BigInteger(), nullable=False),
                    sa.Column('results', sa.String(length=255), nullable=True),
                    sa.Column('away_id', sa.BigInteger(), nullable=False),
                    sa.Column('home_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['away_id'], ['league_team.id'], ),
                    sa.ForeignKeyConstraint(['home_id'], ['league_team.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixture')
    op.drop_table('team_player')
    op.drop_table('league_team')
    op.drop_table('team')
    op.drop_table('season')
    op.drop_table('player')
    op.drop_table('league')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
