"""empty message

Revision ID: f57859043bf7
Revises: bfadb1cc94b8
Create Date: 2021-10-23 21:28:42.400915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57859043bf7'
down_revision = 'bfadb1cc94b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixture', 'match_week',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixture', 'match_week',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
